name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello deploy: ${{ job.status }}."


